[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 9.2

[font.bold]
family = "Jetbrains Mono"
style = "Bold"

[font.italic]
family = "Jetbrains Mono"
style = "Italic"

[font.normal]
family = "Jetbrains Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.96
startup_mode = "Maximized"

[window.padding]
x = 2
y = 2

[general]
import = ["/home/agrses/.config/alacritty/themes/themes/gruvbox_dark.toml"]
